## Objective of this project is to extract data of coronavirus from worldometer by using webscraping and stored in Mysql workbench database

In [2]:
# Importing Libraries
import mysql.connector
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
# Connecting Mysql workbench with jupyter notebook
xyz = mysql.connector.connect(host = 'localhost',user = 'root', password = 'Suman@1289', database = 'ISHU')

In [4]:
myname = xyz.cursor()

In [6]:
# Creating table to store data in database
myname.execute("CREATE TABLE CoronaPatient_Worldwide(DAY INT(2) NOT NULL AUTO_INCREMENT,REGION VARCHAR(20),TOTAL_CASES VARCHAR(20),NEW_CASES VARCHAR(20),TOTAL_DEATHS VARCHAR(20),NEW_DEATHS VARCHAR(20),TOTAL_RECOVERED VARCHAR(20),ACTIVE_CASES VARCHAR(20),SERIOUS VARCHAR(20),PRIMARY KEY (DAY))")

In [4]:
url = "https://www.worldometers.info/coronavirus/"

In [5]:
r = requests.get(url)

In [6]:
soup = BeautifulSoup(r.content,'html.parser')

In [7]:
rows = soup.find_all('tr')

In [8]:
print(rows)

[<tr>
<th width="100">Country,<br>Other</br></th>
<th width="20">Total<br>Cases</br></th>
<th width="30">New<br>Cases</br></th>
<th width="30">Total<br>Deaths</br></th>
<th width="30">New<br>Deaths</br></th>
<th width="30">Total<br>Recovered</br></th>
<th width="30">Active<br>Cases</br></th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th style="display:none" width="30">Continent</th>
</tr>, <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>1,495,849</td>
<td>+23,468</td>
<td>89,954</td>
<td>+1,103</td>
<td>320,040</td>
<td>1,085,855</td>
<td>17,659</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
</tr>, <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>1,628,576</td>
<td>+22,747</td>
<td>152,740</td>
<td>+975</td>
<td>658,498</td>
<td>817,338</td>
<td>13,990</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
</tr>, <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>310,058</td>
<td>+12,104</td>
<td>16,384</td>
<td>+992</td>
<td>108,622</td>
<td>185,052</td>
<td>10,113</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
</tr>, <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>668,605</td>
<td>+17,721</td>
<td>22,172</td>
<td>+321</td>
<td>369,413</td>
<td>277,020</td>
<td>4,995</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
</tr>, <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>64,539</td>
<td>+2,554</td>
<td>2,295</td>
<td>+63</td>
<td>22,600</td>
<td>39,644</td>
<td>235</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
</tr>, <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>8,539</td>
<td>+14</td>
<td>118</td>
<td></td>
<td>7,630</td>
<td>791</td>
<td>20</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
</tr>, <tr class="total_row_world row_continent" data-continent="" style="display: none">
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>651</td>
<td>55</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
</tr>, <tr class="total_row_world">
<td style="text-align:left;">World</td>
<td>4,176,887</td>
<td>+78,608</td>
<td>283,678</td>
<td>+3,454</td>
<td>1,487,454</td>
<td>2,405,755</td>
<td>47,016</td>
<td>536</td>
<td>36.4</td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">1,366,753</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+19,444</td>
<td style="font-weight: bold; text-align:right;">80,757 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+720</td>
<td style="font-weight: bold; text-align:right">255,654</td>
<td style="text-align:right;font-weight:bold;">1,030,342</td>
<td style="font-weight: bold; text-align:right">16,493</td>
<td style="font-weight: bold; text-align:right">4,129</td>
<td style="font-weight: bold; text-align:right">244</td>
<td style="font-weight: bold; text-align:right">9,386,124</td>
<td style="font-weight: bold; text-align:right">28,357</td>
<td data-continent="North America" style="display:none">North America</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">264,663</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,880</td>
<td style="font-weight: bold; text-align:right;">26,621 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+143</td>
<td style="font-weight: bold; text-align:right">176,439</td>
<td style="text-align:right;font-weight:bold;">61,603</td>
<td style="font-weight: bold; text-align:right">1,650</td>
<td style="font-weight: bold; text-align:right">5,661</td>
<td style="font-weight: bold; text-align:right">569</td>
<td style="font-weight: bold; text-align:right">2,467,761</td>
<td style="font-weight: bold; text-align:right">52,781</td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">219,183</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,923</td>
<td style="font-weight: bold; text-align:right;">31,855 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+268</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="text-align:right;font-weight:bold;">186,984</td>
<td style="font-weight: bold; text-align:right">1,559</td>
<td style="font-weight: bold; text-align:right">3,229</td>
<td style="font-weight: bold; text-align:right">469</td>
<td style="font-weight: bold; text-align:right">1,821,280</td>
<td style="font-weight: bold; text-align:right">26,829</td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">219,070</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+802</td>
<td style="font-weight: bold; text-align:right;">30,560 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+165</td>
<td style="font-weight: bold; text-align:right">105,186</td>
<td style="text-align:right;font-weight:bold;">83,324</td>
<td style="font-weight: bold; text-align:right">1,027</td>
<td style="font-weight: bold; text-align:right">3,623</td>
<td style="font-weight: bold; text-align:right">505</td>
<td style="font-weight: bold; text-align:right">2,565,912</td>
<td style="font-weight: bold; text-align:right">42,439</td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">209,688</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+11,012</td>
<td style="font-weight: bold; text-align:right;">1,915 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+88</td>
<td style="font-weight: bold; text-align:right">34,306</td>
<td style="text-align:right;font-weight:bold;">173,467</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">1,437</td>
<td style="font-weight: bold; text-align:right">13</td>
<td style="font-weight: bold; text-align:right">5,448,463</td>
<td style="font-weight: bold; text-align:right">37,335</td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">176,970</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+312</td>
<td style="font-weight: bold; text-align:right;">26,380 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+70</td>
<td style="font-weight: bold; text-align:right">56,217</td>
<td style="text-align:right;font-weight:bold;">94,373</td>
<td style="font-weight: bold; text-align:right">2,776</td>
<td style="font-weight: bold; text-align:right">2,711</td>
<td style="font-weight: bold; text-align:right">404</td>
<td style="font-weight: bold; text-align:right">1,384,633</td>
<td style="font-weight: bold; text-align:right">21,213</td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">171,879</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+555</td>
<td style="font-weight: bold; text-align:right;">7,569 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+20</td>
<td style="font-weight: bold; text-align:right">144,400</td>
<td style="text-align:right;font-weight:bold;">19,910</td>
<td style="font-weight: bold; text-align:right">1,581</td>
<td style="font-weight: bold; text-align:right">2,051</td>
<td style="font-weight: bold; text-align:right">90</td>
<td style="font-weight: bold; text-align:right">2,755,770</td>
<td style="font-weight: bold; text-align:right">32,891</td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">162,699</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,638</td>
<td style="font-weight: bold; text-align:right;">11,123 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+467</td>
<td style="font-weight: bold; text-align:right">64,957</td>
<td style="text-align:right;font-weight:bold;">86,619</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">765</td>
<td style="font-weight: bold; text-align:right">52</td>
<td style="font-weight: bold; text-align:right">339,552</td>
<td style="font-weight: bold; text-align:right">1,597</td>
<td data-continent="South America" style="display:none">South America</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">138,657</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,542</td>
<td style="font-weight: bold; text-align:right;">3,786 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+47</td>
<td style="font-weight: bold; text-align:right">92,691</td>
<td style="text-align:right;font-weight:bold;">42,180</td>
<td style="font-weight: bold; text-align:right">1,154</td>
<td style="font-weight: bold; text-align:right">1,644</td>
<td style="font-weight: bold; text-align:right">45</td>
<td style="font-weight: bold; text-align:right">1,370,598</td>
<td style="font-weight: bold; text-align:right">16,251</td>
<td data-continent="Asia" style="display:none">Asia</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
<td style="font-weight: bold; text-align:right">107,603</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,383</td>
<td style="font-weight: bold; text-align:right;">6,640 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+51</td>
<td style="font-weight: bold; text-align:right">86,143</td>
<td style="text-align:right;font-weight:bold;">14,820</td>
<td style="font-weight: bold; text-align:right">2,675</td>
<td style="font-weight: bold; text-align:right">1,281</td>
<td style="font-weight: bold; text-align:right">79</td>
<td style="font-weight: bold; text-align:right">586,699</td>
<td style="font-weight: bold; text-align:right">6,985</td>
<td data-continent="Asia" style="display:none">Asia</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/canada/">Canada</a></td>
<td style="font-weight: bold; text-align:right">68,848</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,146</td>
<td style="font-weight: bold; text-align:right;">4,870 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+177</td>
<td style="font-weight: bold; text-align:right">32,096</td>
<td style="text-align:right;font-weight:bold;">31,882</td>
<td style="font-weight: bold; text-align:right">502</td>
<td style="font-weight: bold; text-align:right">1,824</td>
<td style="font-weight: bold; text-align:right">129</td>
<td style="font-weight: bold; text-align:right">1,135,984</td>
<td style="font-weight: bold; text-align:right">30,099</td>
<td data-continent="North America" style="display:none">North America</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
<td style="font-weight: bold; text-align:right">67,307</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,292</td>
<td style="font-weight: bold; text-align:right;">1,889 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+75</td>
<td style="font-weight: bold; text-align:right">21,349</td>
<td style="text-align:right;font-weight:bold;">44,069</td>
<td style="font-weight: bold; text-align:right">774</td>
<td style="font-weight: bold; text-align:right">2,041</td>
<td style="font-weight: bold; text-align:right">57</td>
<td style="font-weight: bold; text-align:right">504,930</td>
<td style="font-weight: bold; text-align:right">15,314</td>
<td data-continent="South America" style="display:none">South America</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">67,161</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4,353</td>
<td style="font-weight: bold; text-align:right;">2,212 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+111</td>
<td style="font-weight: bold; text-align:right">20,969</td>
<td style="text-align:right;font-weight:bold;">43,980</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">49</td>
<td style="font-weight: bold; text-align:right">2</td>
<td style="font-weight: bold; text-align:right">1,609,037</td>
<td style="font-weight: bold; text-align:right">1,166</td>
<td data-continent="Asia" style="display:none">Asia</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/belgium/">Belgium</a></td>
<td style="font-weight: bold; text-align:right">53,081</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+485</td>
<td style="font-weight: bold; text-align:right;">8,656 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+75</td>
<td style="font-weight: bold; text-align:right">13,642</td>
<td style="text-align:right;font-weight:bold;">30,783</td>
<td style="font-weight: bold; text-align:right">476</td>
<td style="font-weight: bold; text-align:right">4,580</td>
<td style="font-weight: bold; text-align:right">747</td>
<td style="font-weight: bold; text-align:right">566,101</td>
<td style="font-weight: bold; text-align:right">48,846</td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/netherlands/">Netherlands</a></td>
<td style="font-weight: bold; text-align:right">42,627</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+245</td>
<td style="font-weight: bold; text-align:right;">5,440 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+18</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="text-align:right;font-weight:bold;">36,937</td>
<td style="font-weight: bold; text-align:right">507</td>
<td style="font-weight: bold; text-align:right">2,488</td>
<td style="font-weight: bold; text-align:right">317</td>
<td style="font-weight: bold; text-align:right">254,573</td>
<td style="font-weight: bold; text-align:right">14,857</td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/saudi-arabia/">Saudi Arabia</a></td>
<td style="font-weight: bold; text-align:right">39,048</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,912</td>
<td style="font-weight: bold; text-align:right;">246 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+7</td>
<td style="font-weight: bold; text-align:right">11,457</td>
<td style="text-align:right;font-weight:bold;">27,345</td>
<td style="font-weight: bold; text-align:right">143</td>
<td style="font-weight: bold; text-align:right">1,122</td>
<td style="font-weight: bold; text-align:right">7</td>
<td style="font-weight: bold; text-align:right">449,644</td>
<td style="font-weight: bold; text-align:right">12,916</td>
<td data-continent="Asia" style="display:none">Asia</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
<td style="font-weight: bold; text-align:right">33,460</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,938</td>
<td style="font-weight: bold; text-align:right;">3,353 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+193</td>
<td style="font-weight: bold; text-align:right">21,824</td>
<td style="text-align:right;font-weight:bold;">8,283</td>
<td style="font-weight: bold; text-align:right">378</td>
<td style="font-weight: bold; text-align:right">260</td>
<td style="font-weight: bold; text-align:right">26</td>
<td style="font-weight: bold; text-align:right">128,148</td>
<td style="font-weight: bold; text-align:right">994</td>
<td data-continent="North America" style="display:none">North America</td>
</tr>, <tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/pakistan/">Pakistan</a></td>
<td style="font-weight: bold; text-align:right">30,334</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,598</td>
<td style="font-weight: bold; text-align:right;">659 </td>

In [9]:
s = soup.find_all('div',class_="main_table_countries_today")

In [10]:
b =  soup.find_all('tr',class_="total_row_world")

In [11]:
print(b[7:8])

[<tr class="total_row_world">
<td style="text-align:left;">World</td>
<td>4,176,887</td>
<td>+78,608</td>
<td>283,678</td>
<td>+3,454</td>
<td>1,487,454</td>
<td>2,405,755</td>
<td>47,016</td>
<td>536</td>
<td>36.4</td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
</tr>]

In [12]:
for row in b[7:8]:
    cols = row.find_all('td')
    cols = [x.text.strip() for x in cols]
    print(cols)

['World', '4,176,887', '+78,608', '283,678', '+3,454', '1,487,454', '2,405,755', '47,016', '536', '36.4', '', '', 'All']

In [13]:
cols[0]

'World'

In [14]:
cols[1]

'4,176,887'

In [15]:
Region = cols[0]
Total_Cases = cols[1]
New_Cases = cols[2]
Total_Deaths = cols[3]
New_Deaths = cols[4]
Total_Recovered = cols[5]
Active_Cases = cols[6]
Serious = cols[7]

In [16]:
# Insering data in table of database
sql = "INSERT INTO CoronaPatient_Worldwide(REGION,TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,NEW_DEATHS,TOTAL_RECOVERED,ACTIVE_CASES,SERIOUS) VALUES(%s,%s,%s,%s,%s,%s,%s,%s)"

In [17]:
myname.execute(sql,(Region,Total_Cases,New_Cases,Total_Deaths,New_Deaths,Total_Recovered,Active_Cases,Serious))

In [18]:
xyz.commit()

In [5]:
# Information stored in database
myname.execute("SELECT * FROM CoronaPatient_Worldwide")
myresult = myname.fetchall()
for y in myresult:
    print(y)

(1, 'World', '1,418,730', '+72,726', '81,497', '+6,843', '301,398', '1,035,835', '47,925')
(2, 'World', '1,432,084', '+1,165', '82,099', '+65', '302,209', '1,047,776', '47,895')
(3, 'World', '1,433,055', '+2,136', '82,138', '+104', '302,367', '1,048,550', '47,931')
(4, 'World', '1,444,822', '+13,903', '83,103', '+1,069', '309,110', '1,052,609', '47,980')
(5, 'World', '1,468,842', '+37,923', '85,445', '+3,411', '316,482', '1,066,915', '47,975')
(6, 'World', '1,513,243', '+82,262', '88,403', '+6,367', '329,731', '1,095,109', '48,078')
(7, 'World', '1,518,773', '+813', '88,505', '+50', '330,589', '1,099,679', '48,079')
(8, 'World', '1,538,486', '+20,526', '89,975', '+1,520', '340,521', '1,107,990', '48,512')
(9, 'World', '1,577,747', '+59,787', '93,673', '+5,218', '348,276', '1,135,798', '48,934')
(10, 'World', '1,604,718', '+1,066', '95,735', '+42', '356,660', '1,152,323', '49,128')
(11, 'World', '1,608,331', '+4,679', '95,869', '+177', '358,199', '1,154,263', '49,137')
(12, 'World', '1,617,530', '+13,878', '96,940', '+1,248', '365,795', '1,154,795', '49,185')
(13, 'World', '1,623,336', '+19,684', '97,237', '+1,545', '366,409', '1,159,690', '49,245')
(14, 'World', '1,652,944', '+49,292', '100,379', '+4,687', '369,956', '1,182,609', '50,161')
(15, 'World', '1,681,806', '+78,154', '101,967', '+6,275', '375,093', '1,204,746', '49,814')
(16, 'World', '1,700,378', '+1,543', '102,755', '+71', '376,548', '1,221,075', '49,833')
(17, 'World', '1,710,582', '+11,747', '103,512', '+828', '382,053', '1,225,017', '49,913')
(18, 'World', '1,727,602', '+28,767', '105,722', '+3,038', '390,598', '1,231,282', '50,271')
(19, 'World', '1,763,578', '+64,743', '107,781', '+5,097', '397,053', '1,258,744', '50,041')
(20, 'World', '1,775,510', '+76,629', '108,555', '+5,868', '401,517', '1,265,438', '50,397')
(21, 'World', '1,780,239', '+496', '108,819', '+40', '403,904', '1,267,516', '50,592')
(22, 'World', '1,780,315', '+572', '108,828', '+49', '404,031', '1,267,456', '50,592')
(23, 'World', '1,794,573', '+14,830', '109,918', '+1,139', '411,601', '1,273,054', '50,483')
(24, 'World', '1,831,130', '+51,387', '113,013', '+4,234', '416,980', '1,301,137', '50,653')
(25, 'World', '1,853,155', '+898', '114,247', '+53', '423,625', '1,315,283', '50,853')
(26, 'World', '1,853,505', '+1,248', '114,257', '+63', '423,728', '1,315,520', '50,859')
(27, 'World', '1,871,896', '+19,639', '116,004', '+1,810', '434,298', '1,321,594', '50,794')
(28, 'World', '1,909,180', '+56,923', '118,497', '+4,303', '440,273', '1,350,410', '51,513')
(29, 'World', '1,912,438', '+60,181', '118,683', '+4,489', '441,232', '1,352,523', '51,720')
(30, 'World', '1,925,440', '+1,592', '119,718', '+100', '447,976', '1,357,746', '51,157')
(31, 'World', '1,934,557', '+10,709', '120,438', '+820', '456,737', '1,357,382', '51,151')
(32, 'World', '1,983,219', '+59,371', '125,145', '+5,527', '466,606', '1,391,468', '50,943')
(33, 'World', '1,992,189', '+68,252', '126,066', '+6,448', '467,207', '1,398,916', '51,566')
(34, 'World', '2,014,000', '+16,140', '127,592', '+992', '491,786', '1,394,622', '51,516')
(35, 'World', '2,074,046', '+76,140', '134,072', '+7,471', '509,547', '1,430,427', '51,145')
(36, 'World', '2,083,304', '+932', '134,616', '+56', '510,350', '1,438,338', '51,142')
(37, 'World', '2,094,897', '+12,525', '135,569', '+1,009', '520,946', '1,438,382', '51,092')
(38, 'World', '2,147,601', '+61,170', '144,290', '+5,671', '546,227', '1,457,084', '57,062')
(39, 'World', '2,184,566', '+3,258', '146,897', '+1,426', '553,046', '1,484,623', '56,599')
(40, 'World', '2,193,554', '+12,246', '147,378', '+1,907', '554,815', '1,491,361', '56,566')
(41, 'World', '2,231,438', '+50,130', '150,837', '+5,366', '564,718', '1,515,883', '56,364')
(42, 'World', '2,232,624', '+70,283', '153,292', '+7,821', '568,218', '1,511,114', '56,199')
(43, 'World', '2,265,408', '+16,545', '154,903', '+758', '581,382', '1,529,123', '56,983')
(44, 'World', '2,321,439', '+72,576', '159,625', '+5,480', '594,956', '1,566,858', '55,190')
(45, 'World', '2,359,332', '+28,566', '161,949', '+1,902', '606,675', '1,590,708', '54,526')
(46, 'World', '2,399,849', '+69,083', '164,939', '+4,892', '615,676', '1,619,234', '54,215')
(47, 'World', '2,402,980', '+72,214', '165,641', '+5,594', '615,703', '1,621,636', '54,215')
(48, 'World', '2,418,429', '+11,854', '165,739', '+708', '632,895', '1,619,795', '54,205')
(49, 'World', '2,474,317', '+67,742', '169,932', '+4,901', '645,122', '1,659,263', '56,444')
(50, 'World', '2,475,440', '+68,865', '170,069', '+5,038', '645,214', '1,660,157', '56,444')
(51, 'World', '2,499,546', '+19,043', '171,338', '+941', '658,068', '1,670,140', '57,638')
(52, 'World', '2,552,157', '+71,654', '177,230', '+6,833', '688,412', '1,686,515', '57,254')
(53, 'World', '2,557,917', '+2,157', '177,688', '+229', '695,325', '1,684,904', '57,272')
(54, 'World', '2,585,195', '+29,435', '179,839', '+2,380', '705,691', '1,699,665', '57,204')
(55, 'World', '2,628,469', '+72,709', '183,491', '+6,032', '715,185', '1,729,793', '56,678')
(56, 'World', '2,633,064', '+77,304', '183,882', '+6,423', '717,220', '1,731,962', '56,678')
(57, 'World', '2,714,747', '+82,962', '190,392', '+6,326', '744,886', '1,779,469', '58,675')
(58, 'World', '2,820,935', '+97,766', '196,735', '+5,818', '779,774', '1,844,426', '58,347')
(59, 'World', '2,828,617', '0', '197,091', '0', '798,371', '1,833,155', '58,531')
(60, 'World', '2,874,615', '+45,789', '200,812', '+3,713', '823,306', '1,850,497', '58,276')
(61, 'World', '2,918,934', '+90,108', '203,139', '+6,040', '836,486', '1,879,309', '58,178')
(62, 'World', '2,991,073', '+71,669', '206,822', '+3,658', '877,126', '1,907,125', '57,591')
(63, 'World', '3,135,876', '+75,930', '217,763', '+6,315', '952,942', '1,965,171', '57,307')
(64, 'World', '3,216,808', '+80,300', '227,906', '+6,439', '999,234', '1,989,668', '59,812')
(65, 'World', '3,302,128', '+83,945', '233,745', '+5,716', '1,038,160', '2,030,223', '50,962')
(66, 'World', '3,395,778', '+91,857', '239,350', '+5,526', '1,079,557', '2,076,871', '51,332')
(67, 'World', '3,562,261', '+80,890', '248,094', '+3,431', '1,153,071', '2,161,096', '50,043')
(68, 'World', '3,719,899', '+76,628', '257,747', '+5,506', '1,235,817', '2,226,335', '49,328')
(69, 'World', '3,719,899', '+76,628', '257,747', '+5,506', '1,235,817', '2,226,335', '49,328')
(70, 'World', '3,812,513', '+87,995', '264,109', '+6,083', '1,288,726', '2,259,678', '48,194')
(71, 'World', '3,912,301', '+94,919', '270,348', '+5,511', '1,340,553', '2,301,400', '48,958')
(72, 'World', '4,176,887', '+78,608', '283,678', '+3,454', '1,487,454', '2,405,755', '47,016')

In [10]:
df = pd.DataFrame(myresult,columns = ['Day','Region','Total_cases','New_cases','Total_Deaths','New_Deaths','Total_recovered','Active_cases','Serious'])
df

,Day,Region,Total_cases,New_cases,Total_Deaths,New_Deaths,Total_recovered,Active_cases,Serious
0,1,World,"1,418,730","+72,726","81,497","+6,843","301,398","1,035,835","47,925"
1,2,World,"1,432,084","+1,165","82,099",+65,"302,209","1,047,776","47,895"
2,3,World,"1,433,055","+2,136","82,138",+104,"302,367","1,048,550","47,931"
3,4,World,"1,444,822","+13,903","83,103","+1,069","309,110","1,052,609","47,980"
4,5,World,"1,468,842","+37,923","85,445","+3,411","316,482","1,066,915","47,975"
...,...,...,...,...,...,...,...,...,...
67,68,World,"3,719,899","+76,628","257,747","+5,506","1,235,817","2,226,335","49,328"
68,69,World,"3,719,899","+76,628","257,747","+5,506","1,235,817","2,226,335","49,328"
69,70,World,"3,812,513","+87,995","264,109","+6,083","1,288,726","2,259,678","48,194"
70,71,World,"3,912,301","+94,919","270,348","+5,511","1,340,553","2,301,400","48,958"
71,72,World,"4,176,887","+78,608","283,678","+3,454","1,487,454","2,405,755","47,016"

In [12]:
# Final data about coronavirus
df1 = df.drop(['Day','Region'],axis = 1)

In [13]:
df1

,Total_cases,New_cases,Total_Deaths,New_Deaths,Total_recovered,Active_cases,Serious
0,"1,418,730","+72,726","81,497","+6,843","301,398","1,035,835","47,925"
1,"1,432,084","+1,165","82,099",+65,"302,209","1,047,776","47,895"
2,"1,433,055","+2,136","82,138",+104,"302,367","1,048,550","47,931"
3,"1,444,822","+13,903","83,103","+1,069","309,110","1,052,609","47,980"
4,"1,468,842","+37,923","85,445","+3,411","316,482","1,066,915","47,975"
...,...,...,...,...,...,...,...
67,"3,719,899","+76,628","257,747","+5,506","1,235,817","2,226,335","49,328"
68,"3,719,899","+76,628","257,747","+5,506","1,235,817","2,226,335","49,328"
69,"3,812,513","+87,995","264,109","+6,083","1,288,726","2,259,678","48,194"
70,"3,912,301","+94,919","270,348","+5,511","1,340,553","2,301,400","48,958"
71,"4,176,887","+78,608","283,678","+3,454","1,487,454","2,405,755","47,016"